/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsFlowRouteImport } from './routes/docs.flow'
import { Route as DocsFlowValidateRouteImport } from './routes/docs.flow.validate'
import { Route as DocsFlowStatusRouteImport } from './routes/docs.flow.status'
import { Route as DocsFlowRollbackRouteImport } from './routes/docs.flow.rollback'
import { Route as DocsFlowQuickStartRouteImport } from './routes/docs.flow.quick-start'
import { Route as DocsFlowPlanRouteImport } from './routes/docs.flow.plan'
import { Route as DocsFlowInstallationRouteImport } from './routes/docs.flow.installation'
import { Route as DocsFlowInitRouteImport } from './routes/docs.flow.init'
import { Route as DocsFlowExamplesRouteImport } from './routes/docs.flow.examples'
import { Route as DocsFlowEnhancementsRouteImport } from './routes/docs.flow.enhancements'
import { Route as DocsFlowEnhanceRouteImport } from './routes/docs.flow.enhance'
import { Route as DocsFlowConfigRouteImport } from './routes/docs.flow.config'
import { Route as DocsFlowCommandsRouteImport } from './routes/docs.flow.commands'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFlowRoute = DocsFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFlowValidateRoute = DocsFlowValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowStatusRoute = DocsFlowStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowRollbackRoute = DocsFlowRollbackRouteImport.update({
  id: '/rollback',
  path: '/rollback',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowQuickStartRoute = DocsFlowQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowPlanRoute = DocsFlowPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowInstallationRoute = DocsFlowInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowInitRoute = DocsFlowInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowExamplesRoute = DocsFlowExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowEnhancementsRoute = DocsFlowEnhancementsRouteImport.update({
  id: '/enhancements',
  path: '/enhancements',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowEnhanceRoute = DocsFlowEnhanceRouteImport.update({
  id: '/enhance',
  path: '/enhance',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowConfigRoute = DocsFlowConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DocsFlowRoute,
} as any)
const DocsFlowCommandsRoute = DocsFlowCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsFlowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/flow': typeof FlowRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/flow': typeof DocsFlowRouteWithChildren
  '/docs/flow/commands': typeof DocsFlowCommandsRoute
  '/docs/flow/config': typeof DocsFlowConfigRoute
  '/docs/flow/enhance': typeof DocsFlowEnhanceRoute
  '/docs/flow/enhancements': typeof DocsFlowEnhancementsRoute
  '/docs/flow/examples': typeof DocsFlowExamplesRoute
  '/docs/flow/init': typeof DocsFlowInitRoute
  '/docs/flow/installation': typeof DocsFlowInstallationRoute
  '/docs/flow/plan': typeof DocsFlowPlanRoute
  '/docs/flow/quick-start': typeof DocsFlowQuickStartRoute
  '/docs/flow/rollback': typeof DocsFlowRollbackRoute
  '/docs/flow/status': typeof DocsFlowStatusRoute
  '/docs/flow/validate': typeof DocsFlowValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/flow': typeof FlowRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/flow': typeof DocsFlowRouteWithChildren
  '/docs/flow/commands': typeof DocsFlowCommandsRoute
  '/docs/flow/config': typeof DocsFlowConfigRoute
  '/docs/flow/enhance': typeof DocsFlowEnhanceRoute
  '/docs/flow/enhancements': typeof DocsFlowEnhancementsRoute
  '/docs/flow/examples': typeof DocsFlowExamplesRoute
  '/docs/flow/init': typeof DocsFlowInitRoute
  '/docs/flow/installation': typeof DocsFlowInstallationRoute
  '/docs/flow/plan': typeof DocsFlowPlanRoute
  '/docs/flow/quick-start': typeof DocsFlowQuickStartRoute
  '/docs/flow/rollback': typeof DocsFlowRollbackRoute
  '/docs/flow/status': typeof DocsFlowStatusRoute
  '/docs/flow/validate': typeof DocsFlowValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/flow': typeof FlowRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/flow': typeof DocsFlowRouteWithChildren
  '/docs/flow/commands': typeof DocsFlowCommandsRoute
  '/docs/flow/config': typeof DocsFlowConfigRoute
  '/docs/flow/enhance': typeof DocsFlowEnhanceRoute
  '/docs/flow/enhancements': typeof DocsFlowEnhancementsRoute
  '/docs/flow/examples': typeof DocsFlowExamplesRoute
  '/docs/flow/init': typeof DocsFlowInitRoute
  '/docs/flow/installation': typeof DocsFlowInstallationRoute
  '/docs/flow/plan': typeof DocsFlowPlanRoute
  '/docs/flow/quick-start': typeof DocsFlowQuickStartRoute
  '/docs/flow/rollback': typeof DocsFlowRollbackRoute
  '/docs/flow/status': typeof DocsFlowStatusRoute
  '/docs/flow/validate': typeof DocsFlowValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/flow'
    | '/landing'
    | '/login'
    | '/docs/flow'
    | '/docs/flow/commands'
    | '/docs/flow/config'
    | '/docs/flow/enhance'
    | '/docs/flow/enhancements'
    | '/docs/flow/examples'
    | '/docs/flow/init'
    | '/docs/flow/installation'
    | '/docs/flow/plan'
    | '/docs/flow/quick-start'
    | '/docs/flow/rollback'
    | '/docs/flow/status'
    | '/docs/flow/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/flow'
    | '/landing'
    | '/login'
    | '/docs/flow'
    | '/docs/flow/commands'
    | '/docs/flow/config'
    | '/docs/flow/enhance'
    | '/docs/flow/enhancements'
    | '/docs/flow/examples'
    | '/docs/flow/init'
    | '/docs/flow/installation'
    | '/docs/flow/plan'
    | '/docs/flow/quick-start'
    | '/docs/flow/rollback'
    | '/docs/flow/status'
    | '/docs/flow/validate'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/flow'
    | '/landing'
    | '/login'
    | '/docs/flow'
    | '/docs/flow/commands'
    | '/docs/flow/config'
    | '/docs/flow/enhance'
    | '/docs/flow/enhancements'
    | '/docs/flow/examples'
    | '/docs/flow/init'
    | '/docs/flow/installation'
    | '/docs/flow/plan'
    | '/docs/flow/quick-start'
    | '/docs/flow/rollback'
    | '/docs/flow/status'
    | '/docs/flow/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  FlowRoute: typeof FlowRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/flow': {
      id: '/docs/flow'
      path: '/flow'
      fullPath: '/docs/flow'
      preLoaderRoute: typeof DocsFlowRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/flow/validate': {
      id: '/docs/flow/validate'
      path: '/validate'
      fullPath: '/docs/flow/validate'
      preLoaderRoute: typeof DocsFlowValidateRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/status': {
      id: '/docs/flow/status'
      path: '/status'
      fullPath: '/docs/flow/status'
      preLoaderRoute: typeof DocsFlowStatusRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/rollback': {
      id: '/docs/flow/rollback'
      path: '/rollback'
      fullPath: '/docs/flow/rollback'
      preLoaderRoute: typeof DocsFlowRollbackRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/quick-start': {
      id: '/docs/flow/quick-start'
      path: '/quick-start'
      fullPath: '/docs/flow/quick-start'
      preLoaderRoute: typeof DocsFlowQuickStartRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/plan': {
      id: '/docs/flow/plan'
      path: '/plan'
      fullPath: '/docs/flow/plan'
      preLoaderRoute: typeof DocsFlowPlanRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/installation': {
      id: '/docs/flow/installation'
      path: '/installation'
      fullPath: '/docs/flow/installation'
      preLoaderRoute: typeof DocsFlowInstallationRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/init': {
      id: '/docs/flow/init'
      path: '/init'
      fullPath: '/docs/flow/init'
      preLoaderRoute: typeof DocsFlowInitRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/examples': {
      id: '/docs/flow/examples'
      path: '/examples'
      fullPath: '/docs/flow/examples'
      preLoaderRoute: typeof DocsFlowExamplesRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/enhancements': {
      id: '/docs/flow/enhancements'
      path: '/enhancements'
      fullPath: '/docs/flow/enhancements'
      preLoaderRoute: typeof DocsFlowEnhancementsRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/enhance': {
      id: '/docs/flow/enhance'
      path: '/enhance'
      fullPath: '/docs/flow/enhance'
      preLoaderRoute: typeof DocsFlowEnhanceRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/config': {
      id: '/docs/flow/config'
      path: '/config'
      fullPath: '/docs/flow/config'
      preLoaderRoute: typeof DocsFlowConfigRouteImport
      parentRoute: typeof DocsFlowRoute
    }
    '/docs/flow/commands': {
      id: '/docs/flow/commands'
      path: '/commands'
      fullPath: '/docs/flow/commands'
      preLoaderRoute: typeof DocsFlowCommandsRouteImport
      parentRoute: typeof DocsFlowRoute
    }
  }
}

interface DocsFlowRouteChildren {
  DocsFlowCommandsRoute: typeof DocsFlowCommandsRoute
  DocsFlowConfigRoute: typeof DocsFlowConfigRoute
  DocsFlowEnhanceRoute: typeof DocsFlowEnhanceRoute
  DocsFlowEnhancementsRoute: typeof DocsFlowEnhancementsRoute
  DocsFlowExamplesRoute: typeof DocsFlowExamplesRoute
  DocsFlowInitRoute: typeof DocsFlowInitRoute
  DocsFlowInstallationRoute: typeof DocsFlowInstallationRoute
  DocsFlowPlanRoute: typeof DocsFlowPlanRoute
  DocsFlowQuickStartRoute: typeof DocsFlowQuickStartRoute
  DocsFlowRollbackRoute: typeof DocsFlowRollbackRoute
  DocsFlowStatusRoute: typeof DocsFlowStatusRoute
  DocsFlowValidateRoute: typeof DocsFlowValidateRoute
}

const DocsFlowRouteChildren: DocsFlowRouteChildren = {
  DocsFlowCommandsRoute: DocsFlowCommandsRoute,
  DocsFlowConfigRoute: DocsFlowConfigRoute,
  DocsFlowEnhanceRoute: DocsFlowEnhanceRoute,
  DocsFlowEnhancementsRoute: DocsFlowEnhancementsRoute,
  DocsFlowExamplesRoute: DocsFlowExamplesRoute,
  DocsFlowInitRoute: DocsFlowInitRoute,
  DocsFlowInstallationRoute: DocsFlowInstallationRoute,
  DocsFlowPlanRoute: DocsFlowPlanRoute,
  DocsFlowQuickStartRoute: DocsFlowQuickStartRoute,
  DocsFlowRollbackRoute: DocsFlowRollbackRoute,
  DocsFlowStatusRoute: DocsFlowStatusRoute,
  DocsFlowValidateRoute: DocsFlowValidateRoute,
}

const DocsFlowRouteWithChildren = DocsFlowRoute._addFileChildren(
  DocsFlowRouteChildren,
)

interface DocsRouteChildren {
  DocsFlowRoute: typeof DocsFlowRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsFlowRoute: DocsFlowRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  FlowRoute: FlowRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
