import { createFileRoute } from '@tanstack/react-router'
import DocsLayout from '@/components/docs/docs-layout'
import { CodeBlock } from '@/components/ui/code-block'

export const Route = createFileRoute('/docs/flow/rollback')({
  component: RouteComponent,
})

function RouteComponent() {
  return (
    <DocsLayout>
      <div className="prose prose-gray dark:prose-invert max-w-none">
        <h1>↩️ flow rollback</h1>
        <p className="lead">
          Generate a rollback script to undo a migration. This is a critical safety feature for recovering from failed deployments.
        </p>

        <h2>Quick Start</h2>
        <CodeBlock
          variant="fancy"
          code={`# Generate rollback for the latest migration
$ flow rollback

# Generate rollback for a specific migration file
$ flow rollback migrations/20240101000001_add_users.sql

# Output rollback script to a file
$ flow rollback > rollback_script.sql`}
        />

        <h2>Overview</h2>
        <p>
          The <code>flow rollback</code> command analyzes a migration and generates the corresponding SQL to reverse its operations. It intelligently inverts common DDL statements.
        </p>

        <h2>How It Works</h2>
        <p>
          Flow parses the migration file and maps each SQL operation to its inverse:
        </p>
        <ul>
          <li><code>CREATE TABLE</code> ↔️ <code>DROP TABLE</code></li>
          <li><code>ADD COLUMN</code> ↔️ <code>DROP COLUMN</code></li>
          <li><code>CREATE INDEX</code> ↔️ <code>DROP INDEX</code></li>
        </ul>

        <h2>Command Options</h2>
        <table>
          <thead>
            <tr>
              <th>Option</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>[file]</code></td>
              <td>Specific migration file to roll back (optional, defaults to latest)</td>
            </tr>
            <tr>
              <td><code>--project &lt;path&gt;</code></td>
              <td>Path to your project directory</td>
            </tr>
          </tbody>
        </table>

        <h2>Example</h2>
        <p><strong>Given Migration:</strong></p>
        <CodeBlock
          variant="fancy"
          code={`CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255));
ALTER TABLE users ADD COLUMN age INT;
CREATE INDEX idx_email ON users(email);`}
        />

        <p><strong>Generated Rollback Script:</strong></p>
        <CodeBlock
          variant="fancy"
          code={`-- Rollback script generated by Flow
DROP INDEX idx_email;
ALTER TABLE users DROP COLUMN age;
DROP TABLE users;`}
        />
      </div>
    </DocsLayout>
  )
} 